- name: Bacnk server 
  hosts: backend
  become: yes
  tasks:
  - name: Disable Nodejs 18
    ansible.builtin.command: dnf module disable nodejs -y
    ignore_errors: true

  - name: Enabel  Nodejs 20 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install Nodejs
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: 
    - nodejs
    - mysql

  - name: Add user 
    ansible.builtin.user:
    name: expense
  - name: Create App directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download application to path
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Extract code 
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes
  - name: install nmp
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copy backend service 
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service
 
  - name: ansible to install pymysql
    ansible.builtin.pip:
      name:
      - pymysql
      - crypto                                  
      excutable: pip3
  
  - name: Import mysql data
    community.mysql.mysql_db:
      login_user: root
      login_password: "{{ root_password }}"
      login_host: "{{ login_host }}" 
      target: /app/schema/backend.sql
      name: all 
      state: import