- name: configure front server
  hosts: frontend
  become: yes
  tasks:
  - name: Install nginx 
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx service
    ansible.builtin.service:
      name: nginx
      status: started
      enabled: yes

  - name: remove exiting confirguration
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  
  - name: Download application to path
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: Extract code 
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
 
  - name: Copy expence conf 
    ansible.builtin.copy:
      src: expense.conf
      dest: /ect/nginx/default.d/expense.conf
  - name: Restart nginx 
    ansible.builtin.service:
      name: nginx
      state: restarted 